# Generated by Django 4.2.16 on 2025-11-29 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.IntegerField(
                default=0,
                help_text="Discount percentage (0-100). Only applicable when on_sale is True.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new_arrival",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="on_sale",
            field=models.BooleanField(default=False),
        ),
    ]
