# Generated by Django 4.2.16 on 2025-11-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_config_address_config_email_config_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
